name: "security workflow"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run_42c_audit:
    environment: 42Crunch
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: 42crunch-static-api-testing
        uses: api-security-audit-action-freemium@main
