name: Security Audit

on:
  workflow_dispatch:

jobs:
  run_42c_audit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: 42crunch-static-api-testing
        uses: api-security-audit-action-freemium@main
