name: Security Audit

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run_42c_audit:
    name: 42Crunch API Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

#      - name: 42crunch-static-api-testing
#        uses: 42crunch/api-security-audit-action-freemium@main

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: audit-report.json.report
          # Optional category for the results
          # Used to differentiate multiple results for one commit
